In [1]:
import pandas as pd
import os
from pathlib import Path
import re

In [2]:
if 'notebooks' in os.getcwd():
    print("Still in notebooks/ directory. Changing to root directory..")
    os.chdir('..')
print(f"Already in root directory: {os.getcwd()}")

Still in notebooks/ directory. Changing to root directory..
Already in root directory: d:\data-sci-projects\aer-data-extraction

In [4]:
os.listdir('data/processed')

['rin_maintenance_cost_metrics.csv',
 'rin_maintenance_descriptor_metrics.csv',
 'rin_maintenance_run_report.csv']

In [5]:
desc = pd.read_csv('data/processed/rin_maintenance_descriptor_metrics.csv')
cost = pd.read_csv('data/processed/rin_maintenance_cost_metrics.csv')

In [6]:
desc

,reporting_period,maintenance_activity,maintenance_asset_category,measure_asset_quantity,source_unit,asset_quantity_at_year_end,quantity_inspected_maintained,average_age_of_asset_group,inspection_cycle_years,maintenance_cycle_years,source_workbook,source_sheet,source_row
0,2020-21,Transmission lines maintenance,Transmission towers,Number of towers,0's,13206.00000,14673.333333,50.790550,1.0,9.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,12
1,2020-21,Transmission lines maintenance,Transmission tower support structures,Number of towers,0's,69605.00000,46403.333333,50.046254,3.0,3.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,13
2,2020-21,Transmission lines maintenance,Conductors,Route length,km,5024.70000,1674.900000,40.189053,3.0,0.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,14
3,2020-21,Transmission lines maintenance,Transmission cables,Route length,km,8.54237,17.084741,27.135000,1.0,1.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,15
4,2020-21,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),Number of switchbays,0's,1158.00000,2173.000000,22.467680,1.0,6.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2023-24,Substations equipment & property maintenance,Substation property,Number of substation properties maintained,number,96.00000,95.000000,39.900000,0.5,0.3,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,19
248,2023-24,SCADA & network control maintenance,SCADA & network control maintenance,Number of main control assets,0's,2046.00000,196.000000,12.600000,NaN,NaN,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,20
249,2023-24,Protection systems maintenance,Protection systems maintenance,Number of main protection assets,0's,3286.00000,893.000000,15.600000,NaN,6.5,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,21
250,2023-24,Other maintenance activity,Metering,Number of main metering assets,0's,838.00000,639.000000,10.700000,2.5,5.0,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,22
251,2023-24,NaN,Communications,Number of main communications assets,0's,1790.00000,974.000000,10.600000,1.0,3.0,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,23

In [7]:
cost

,reporting_period,maintenance_activity,maintenance_asset_subcategory,source_currency_unit,routine_maintenance_expenditure,non_routine_maintenance_expenditure,source_workbook,source_sheet,source_row
0,2020-21,Transmission lines maintenance,Transmission towers,$0's,8.056913e+05,9.381098e+05,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,50
1,2020-21,Transmission lines maintenance,Transmission tower support structures,$0's,2.496602e+05,1.047950e+05,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,51
2,2020-21,Transmission lines maintenance,Conductors,$0's,1.301578e+06,1.269285e+05,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,52
3,2020-21,Transmission lines maintenance,Transmission cables,$0's,7.727257e+03,3.535977e+04,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,53
4,2020-21,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),$0's,2.718726e+06,2.782993e+06,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,54
...,...,...,...,...,...,...,...,...,...
251,2023-24,Substations equipment & property maintenance,Substation property,$,6.745046e+06,4.178675e+06,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,57
252,2023-24,SCADA & network control maintenance,SCADA & network control maintenance,$,2.443070e+05,7.348910e+05,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,58
253,2023-24,Protection systems maintenance,Protection systems maintenance,$,9.816660e+05,8.727580e+05,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,59
254,2023-24,Other maintenance activity,Metering,$,5.329630e+05,2.245490e+05,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,60
255,2023-24,NaN,Communications,$,3.454410e+05,1.626967e+06,Transgrid 2023-24 - Category Analysis - RIN Re...,2.8 Maintenance,61