In [17]:
import pandas as pd
import os
from pathlib import Path
import re

In [3]:
if 'notebooks' in os.getcwd():
    print("Still in notebooks/ directory. Changing to root directory..")
    os.chdir('..')
print(f"Already in root directory: {os.getcwd()}")

Still in notebooks/ directory. Changing to root directory..
Already in root directory: d:\data-sci-projects\aer-data-extraction

In [10]:
excel_files = [f for f in Path('./data/raw').iterdir() if 'xlsx' in str(f).lower() or 'xlsm' in str(f).lower()]
list(enumerate(excel_files))

[(0,
  WindowsPath('data/raw/AusNet (T) 2020-21 - Category Analysis - RIN Response - Consolidated - 29 July 2021 - PU(12595757.1).xlsx')),
 (1,
  WindowsPath('data/raw/AusNet (T) 2021-22 - Category Analysis - RIN Response - Consolidated - 28 July 2022 - PUBLIC(14205738.1).xlsx')),
 (2,
  WindowsPath('data/raw/Ausnet Services (ET) 2022-23 - Category Analysis - RIN Response - Consolidated - 28 July 2023 - PUBLIC(15600825.1).xlsx')),
 (3,
  WindowsPath('data/raw/Ausnet Services (ET) 2023-24 - Category Analysis - RIN Response - Consolidated - 26 July 2024 - PUBLIC(17069098.2).xlsx')),
 (4,
  WindowsPath('data/raw/Copy of D14-00150087(V02) - transgrid (t) 2013-14 - category analysis rin response - templates - consolidated - 31 october 2014 - public.xlsm')),
 (5,
  WindowsPath('data/raw/Copy of D16 147530(V3)  ElectraNet 2015-16 - Category Analysis RIN Response - Public Version - 31 October 2016 - PUBLIC.xlsm')),
 (6,
  WindowsPath('data/raw/Copy of D17 153782  ElectraNet 2016-17 - Category Analysis RIN - Template - 31 October 2017 - PUBLIC.xlsm')),
 (7,
  WindowsPath('data/raw/DORIS - D18-158142 Transgrid 2017-18 - Category Analysis RIN - Templates - Public.XLSM')),
 (8,
  WindowsPath('data/raw/DORIS - D18-158267 ElectraNet 2017-18 - Category Analysis RIN - Template - Public.XLSM')),
 (9,
  WindowsPath('data/raw/ElectraNet 2018-19 - Category Analysis - RIN Response - Consolidated - 31 October 2019 - PUBLIC D19-175655.xlsx')),
 (10,
  WindowsPath('data/raw/ElectraNet 2019-20 - Category Analysis - RIN Response - Consolidated - 30 October 2020 - PUBLIC (#11672792).xlsx')),
 (11,
  WindowsPath('data/raw/ElectraNet 2020-21 - Category Analysis - RIN Response - Consolidated - 29 October 2021 - PUBLIC(13029806.1).xlsx')),
 (12,
  WindowsPath('data/raw/ElectraNet 2021-22 - Category Analysis - RIN response - 28 October 2022 - PUBLIC(14582813.1).xlsx')),
 (13,
  WindowsPath('data/raw/ElectraNet 2022-23 - Category analysis - RIN responses - Consolidated - 27 October 2023 - PUBLIC(15999621.1).xlsx')),
 (14,
  WindowsPath('data/raw/ElectraNet 2023-24 - Category Analysis - RIN response - Consolidated - 31 October 2024 - PUBLIC(17494700.2).xlsx')),
 (15,
  WindowsPath('data/raw/Powerlink 2020-21 - Category Analysis - RIN Response - Consolidated - 20 October 2021 - PUBLIC(12941266.1).xlsx')),
 (16,
  WindowsPath('data/raw/Powerlink 2021-22 - Category analysis - Consolidated - 26 October 2022 - PUBLIC(14556313.1).xlsx')),
 (17,
  WindowsPath('data/raw/Powerlink 2022-23 - Category Analysis - RIN Response - Consolidated - 27 October 2023 - PUBLIC(15996094.1).xlsx')),
 (18,
  WindowsPath('data/raw/Powerlink 2023-24 - Category Analysis - RIN Response - Consolidated - 28 October 2024 - PUBLIC(17452408.1).xlsx')),
 (19,
  WindowsPath('data/raw/Transgrid 2018-19 - Category Analysis - RIN Response - Consolidated - 31 October 2019 - PUBLIC D19-175594.XLSM.xlsx')),
 (20,
  WindowsPath('data/raw/TransGrid 2019-20 - Category Analysis - RIN Response - Consolidated - 30 October 2020 - PUBLIC (#11,665,158).xlsx')),
 (21,
  WindowsPath('data/raw/TransGrid 2020-21 - Category Analysis - RIN Response - Consolidated - 29 October 2021 - PUBLIC(13029988.1).xlsx')),
 (22,
  WindowsPath('data/raw/Transgrid 2022-23 - Category analysis - RIN response - Consolidated - 31 October 2023 - PUBLIC(15993699.2).xlsx')),
 (23,
  WindowsPath('data/raw/Transgrid 2023-24 - Category Analysis - RIN Response - Consolidated - 31 October 2024 - PUBLIC(17496053.2).xlsx'))]

In [5]:
file = pd.ExcelFile(excel_files[0])
file.sheet_names

['Instructions',
 'CONTENTS',
 'Business & other details',
 '2.1 Expenditure summary',
 '2.2 Repex',
 '2.3 Augex',
 '2.5 Connections',
 '2.6 Non-network',
 '2.7 Vegetation management',
 '2.8 Maintenance',
 '2.10(A) Overheads',
 '2.11 Labour',
 '2.12 Input tables',
 '5.2 Asset Age Profile',
 '5.3 MD - Network level',
 '5.4 MD & utilisation-Spatial',
 'Amendments']

In [32]:
excel_files[chosen_idx].name

'AusNet (T) 2020-21 - Category Analysis - RIN Response - Consolidated - 29 July 2021 - PU(12595757.1).xlsx'

In [39]:
from src.rin_maintenance_heading_extractor import extract_rin_maintenance

In [41]:
excel_files

[WindowsPath('data/raw/AusNet (T) 2020-21 - Category Analysis - RIN Response - Consolidated - 29 July 2021 - PU(12595757.1).xlsx'),
 WindowsPath('data/raw/AusNet (T) 2021-22 - Category Analysis - RIN Response - Consolidated - 28 July 2022 - PUBLIC(14205738.1).xlsx'),
 WindowsPath('data/raw/Ausnet Services (ET) 2022-23 - Category Analysis - RIN Response - Consolidated - 28 July 2023 - PUBLIC(15600825.1).xlsx'),
 WindowsPath('data/raw/Ausnet Services (ET) 2023-24 - Category Analysis - RIN Response - Consolidated - 26 July 2024 - PUBLIC(17069098.2).xlsx'),
 WindowsPath('data/raw/Copy of D14-00150087(V02) - transgrid (t) 2013-14 - category analysis rin response - templates - consolidated - 31 october 2014 - public.xlsm'),
 WindowsPath('data/raw/Copy of D16 147530(V3)  ElectraNet 2015-16 - Category Analysis RIN Response - Public Version - 31 October 2016 - PUBLIC.xlsm'),
 WindowsPath('data/raw/Copy of D17 153782  ElectraNet 2016-17 - Category Analysis RIN - Template - 31 October 2017 - PUBLIC.xlsm'),
 WindowsPath('data/raw/DORIS - D18-158142 Transgrid 2017-18 - Category Analysis RIN - Templates - Public.XLSM'),
 WindowsPath('data/raw/DORIS - D18-158267 ElectraNet 2017-18 - Category Analysis RIN - Template - Public.XLSM'),
 WindowsPath('data/raw/ElectraNet 2018-19 - Category Analysis - RIN Response - Consolidated - 31 October 2019 - PUBLIC D19-175655.xlsx'),
 WindowsPath('data/raw/ElectraNet 2019-20 - Category Analysis - RIN Response - Consolidated - 30 October 2020 - PUBLIC (#11672792).xlsx'),
 WindowsPath('data/raw/ElectraNet 2020-21 - Category Analysis - RIN Response - Consolidated - 29 October 2021 - PUBLIC(13029806.1).xlsx'),
 WindowsPath('data/raw/ElectraNet 2021-22 - Category Analysis - RIN response - 28 October 2022 - PUBLIC(14582813.1).xlsx'),
 WindowsPath('data/raw/ElectraNet 2022-23 - Category analysis - RIN responses - Consolidated - 27 October 2023 - PUBLIC(15999621.1).xlsx'),
 WindowsPath('data/raw/ElectraNet 2023-24 - Category Analysis - RIN response - Consolidated - 31 October 2024 - PUBLIC(17494700.2).xlsx'),
 WindowsPath('data/raw/Powerlink 2020-21 - Category Analysis - RIN Response - Consolidated - 20 October 2021 - PUBLIC(12941266.1).xlsx'),
 WindowsPath('data/raw/Powerlink 2021-22 - Category analysis - Consolidated - 26 October 2022 - PUBLIC(14556313.1).xlsx'),
 WindowsPath('data/raw/Powerlink 2022-23 - Category Analysis - RIN Response - Consolidated - 27 October 2023 - PUBLIC(15996094.1).xlsx'),
 WindowsPath('data/raw/Powerlink 2023-24 - Category Analysis - RIN Response - Consolidated - 28 October 2024 - PUBLIC(17452408.1).xlsx'),
 WindowsPath('data/raw/Transgrid 2018-19 - Category Analysis - RIN Response - Consolidated - 31 October 2019 - PUBLIC D19-175594.XLSM.xlsx'),
 WindowsPath('data/raw/TransGrid 2019-20 - Category Analysis - RIN Response - Consolidated - 30 October 2020 - PUBLIC (#11,665,158).xlsx'),
 WindowsPath('data/raw/TransGrid 2020-21 - Category Analysis - RIN Response - Consolidated - 29 October 2021 - PUBLIC(13029988.1).xlsx'),
 WindowsPath('data/raw/Transgrid 2022-23 - Category analysis - RIN response - Consolidated - 31 October 2023 - PUBLIC(15993699.2).xlsx'),
 WindowsPath('data/raw/Transgrid 2023-24 - Category Analysis - RIN Response - Consolidated - 31 October 2024 - PUBLIC(17496053.2).xlsx')]

In [40]:
# # hardcoded selection of RIN workbooks for now,
# # covering RIN workbooks from different businesses 
for chosen_idx in [0, 2, 5, 15, 22]:
    result = extract_rin_maintenance(excel_files[chosen_idx])

    display(result.descriptor_metrics)
    display(result.cost_metrics)
    display(result.header_locations)
    result.warnings
#     print(f"------ SAVING {excel_files[chosen_idx]}... ------")
#     df = pd.read_excel(excel_files[chosen_idx], sheet_name='2.8 Maintenance', engine='openpyxl')
#     df.to_csv(f'.agents/[read_excel]{excel_files[chosen_idx].name}.csv')

[maintenance] Opening data\raw\AusNet (T) 2020-21 - Category Analysis - RIN Response - Consolidated - 29 July 2021 - PU(12595757.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10

,reporting_period,maintenance_activity,maintenance_asset_category,measure_asset_quantity,source_unit,asset_quantity_at_year_end,quantity_inspected_maintained,average_age_of_asset_group,inspection_cycle_years,maintenance_cycle_years,source_workbook,source_sheet,source_row
0,2020-21,Transmission lines maintenance,Transmission towers,Number of towers,0's,13206.00000,14673.333333,50.790550,1.000,9.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,12
1,2020-21,Transmission lines maintenance,Transmission tower support structures,Number of towers,0's,69605.00000,46403.333333,50.046254,3.000,3.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,13
2,2020-21,Transmission lines maintenance,Conductors,Route length,km,5024.70000,1674.900000,40.189053,3.000,0.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,14
3,2020-21,Transmission lines maintenance,Transmission cables,Route length,km,8.54237,17.084741,27.135000,1.000,1.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,15
4,2020-21,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),Number of switchbays,0's,1158.00000,2173.000000,22.467680,1.000,6.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,16
5,2020-21,Substations equipment & property maintenance,Substation power transformers,Number of transformers,0's,173.00000,1173.000000,29.118497,1.000,4.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,17
6,2020-21,Substations equipment & property maintenance,Substation property,Number of substation properties maintained,0's,47.00000,1277.000000,30.000000,0.083,0.5,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,18
7,2020-21,SCADA & network control maintenance,SCADA & network control maintenance,Units,NaN,20989.54821,10494.774105,17.728515,4.000,4.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,19
8,2020-21,Protection systems maintenance,Protection systems maintenance,Units,NaN,6555.00000,4370.000000,16.516154,3.000,3.0,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,20
9,2020-21,Other maintenance activity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,21

,reporting_period,maintenance_activity,maintenance_asset_subcategory,source_currency_unit,routine_maintenance_expenditure,non_routine_maintenance_expenditure,source_workbook,source_sheet,source_row
0,2020-21,Transmission lines maintenance,Transmission towers,$0's,8.056913e+05,9.381098e+05,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,50
1,2020-21,Transmission lines maintenance,Transmission tower support structures,$0's,2.496602e+05,1.047950e+05,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,51
2,2020-21,Transmission lines maintenance,Conductors,$0's,1.301578e+06,1.269285e+05,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,52
3,2020-21,Transmission lines maintenance,Transmission cables,$0's,7.727257e+03,3.535977e+04,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,53
4,2020-21,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),$0's,2.718726e+06,2.782993e+06,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,54
5,2020-21,Substations equipment & property maintenance,Substation power transformers,$0's,1.804333e+06,2.396226e+06,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,55
6,2020-21,Substations equipment & property maintenance,Substation property,$0's,3.735239e+05,2.917833e+06,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,56
7,2020-21,SCADA & network control maintenance,SCADA & network control maintenance,$0's,4.941780e+05,6.027625e+05,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,57
8,2020-21,Protection systems maintenance,Protection systems maintenance,$0's,6.104529e+05,1.055964e+06,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,58
9,2020-21,Other maintenance activity,NaN,$0's,NaN,NaN,AusNet (T) 2020-21 - Category Analysis - RIN R...,2.8 Maintenance,59

{'descriptor_metrics': {'maintenance_activity': 'B10',
  'maintenance_asset_category': 'C10',
  'measure_asset_quantity': 'D10',
  'source_unit': 'E10',
  'asset_quantity_at_year_end': 'F10',
  'quantity_inspected_maintained': 'G10',
  'average_age_of_asset_group': 'H9',
  'inspection_cycle_years': 'I9',
  'maintenance_cycle_years': 'J9'},
 'cost_metrics': {'maintenance_activity': 'B48',
  'maintenance_asset_subcategory': 'C48',
  'routine_maintenance_expenditure': 'F48',
  'non_routine_maintenance_expenditure': 'G48',
  'source_currency_unit': 'F47'}}

[maintenance] Opening data\raw\Ausnet Services (ET) 2022-23 - Category Analysis - RIN Response - Consolidated - 28 July 2023 - PUBLIC(15600825.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10

,reporting_period,maintenance_activity,maintenance_asset_category,measure_asset_quantity,source_unit,asset_quantity_at_year_end,quantity_inspected_maintained,average_age_of_asset_group,inspection_cycle_years,maintenance_cycle_years,source_workbook,source_sheet,source_row
0,2022-23,Transmission lines maintenance,Transmission towers,Number of towers,0's,13196.00000,14662.222222,52.797709,1.000,9.0,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,12
1,2022-23,Transmission lines maintenance,Transmission tower support structures,Number of towers,0's,70616.00000,47077.333333,50.040934,3.000,3.0,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,13
2,2022-23,Transmission lines maintenance,Conductors,Route length,km,6611.46500,2203.821667,46.171430,3.000,0.0,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,14
3,2022-23,Transmission lines maintenance,Transmission cables,Route length,km,8.54237,17.084741,29.135000,1.000,1.0,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,15
4,2022-23,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),Number of switchbays,0's,1218.00000,8005.000000,21.963876,1.000,6.0,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,16
5,2022-23,Substations equipment & property maintenance,Substation power transformers,Number of transformers,0's,184.00000,2095.000000,28.101227,1.000,4.0,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,17
6,2022-23,Substations equipment & property maintenance,Substation property,Number of substation properties maintained,0's,47.00000,1857.000000,41.965217,0.083,0.5,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,18
7,2022-23,SCADA & network control maintenance,SCADA & network control maintenance,Units,NaN,20981.11759,10490.558795,19.335685,4.000,4.0,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,19
8,2022-23,Protection systems maintenance,Protection systems maintenance,Units,NaN,6681.00000,4454.000000,16.097225,3.000,3.0,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,20
9,2022-23,Other maintenance activity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,21

,reporting_period,maintenance_activity,maintenance_asset_subcategory,source_currency_unit,routine_maintenance_expenditure,non_routine_maintenance_expenditure,source_workbook,source_sheet,source_row
0,2022-23,Transmission lines maintenance,Transmission towers,$0's,3.033506e+05,1.861518e+05,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,50
1,2022-23,Transmission lines maintenance,Transmission tower support structures,$0's,4.311113e+05,3.154237e+04,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,51
2,2022-23,Transmission lines maintenance,Conductors,$0's,6.495503e+05,1.112531e+04,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,52
3,2022-23,Transmission lines maintenance,Transmission cables,$0's,2.811912e+03,5.973352e+03,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,53
4,2022-23,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),$0's,5.181951e+06,8.463585e+06,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,54
5,2022-23,Substations equipment & property maintenance,Substation power transformers,$0's,1.032729e+06,8.734008e+05,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,55
6,2022-23,Substations equipment & property maintenance,Substation property,$0's,4.519813e+05,8.914207e+05,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,56
7,2022-23,SCADA & network control maintenance,SCADA & network control maintenance,$0's,6.207017e+05,1.535681e+05,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,57
8,2022-23,Protection systems maintenance,Protection systems maintenance,$0's,6.519170e+05,1.040363e+06,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,58
9,2022-23,Other maintenance activity,NaN,$0's,NaN,NaN,Ausnet Services (ET) 2022-23 - Category Analys...,2.8 Maintenance,59

{'descriptor_metrics': {'maintenance_activity': 'B10',
  'maintenance_asset_category': 'C10',
  'measure_asset_quantity': 'D10',
  'source_unit': 'E10',
  'asset_quantity_at_year_end': 'F10',
  'quantity_inspected_maintained': 'G10',
  'average_age_of_asset_group': 'H9',
  'inspection_cycle_years': 'I9',
  'maintenance_cycle_years': 'J9'},
 'cost_metrics': {'maintenance_activity': 'B48',
  'maintenance_asset_subcategory': 'C48',
  'routine_maintenance_expenditure': 'F48',
  'non_routine_maintenance_expenditure': 'G48',
  'source_currency_unit': 'F47'}}

[maintenance] Opening data\raw\Copy of D16 147530(V3)  ElectraNet 2015-16 - Category Analysis RIN Response - Public Version - 31 October 2016 - PUBLIC.xlsm
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Warning: descriptor_metrics: nonnumeric values in maintenance_cycle_years: row 12: 'Nil. Cond mon.&corr mtce'; row 13: 'Nil. Cond mon.&corr mtce'; row 14: 'Nil. Cond mon.&corr mtce'; row 15: 'Nil. Cond mon.&corr mtce'; row 19: 'Nil. Cond mon.&corr mtce'
[maintenance] Warning: descriptor_metrics: unrecognized source units in source_unit: ["000' KM"]

,reporting_period,maintenance_activity,maintenance_asset_category,measure_asset_quantity,source_unit,asset_quantity_at_year_end,quantity_inspected_maintained,average_age_of_asset_group,inspection_cycle_years,maintenance_cycle_years,source_workbook,source_sheet,source_row
0,2015-16,Transmission lines maintenance,Transmission towers,Number of towers,0's,13.253,13.253,44.3,0.50,Nil. Cond mon.&corr mtce,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,12
1,2015-16,Transmission lines maintenance,Transmission tower support structures,Number of towers,0's,58.668,58.668,42.0,0.50,Nil. Cond mon.&corr mtce,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,13
2,2015-16,Transmission lines maintenance,Conductors,Route length,km,5.497,5.497,42.7,0.50,Nil. Cond mon.&corr mtce,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,14
3,2015-16,Transmission lines maintenance,Transmission cables,Route length,km,0.027,0.027,12.5,0.02,Nil. Cond mon.&corr mtce,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,15
4,2015-16,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),Number of switchbays,0's,1.346,1.346,22.7,0.25,6,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,16
5,2015-16,Substations equipment & property maintenance,Substation power transformers,Number of transformers,0's,0.139,0.139,29.1,0.25,6,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,17
6,2015-16,Substations equipment & property maintenance,Substation property,Number of substation properties maintained,0's,0.077,0.077,37.9,0.25,0.5,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,18
7,2015-16,SCADA & network control maintenance,SCADA & network control maintenance,Number of comms sites,0's,120.000,120.000,30.0,0.50,Nil. Cond mon.&corr mtce,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,19
8,2015-16,Protection systems maintenance,Protection systems maintenance,Number of protection systems,0's,1362.000,1362.000,13.6,0.25,4,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,20
9,2015-16,Right of way (Row) maintenance,Row Maintenance,Length (Route Km),000' km,4.539,4.539,42.7,0.50,3,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,21

,reporting_period,maintenance_activity,maintenance_asset_subcategory,source_currency_unit,routine_maintenance_expenditure,non_routine_maintenance_expenditure,source_workbook,source_sheet,source_row
0,2015-16,Transmission lines maintenance,Transmission towers,$0's,2.009279e+06,7.210284e+06,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,50
1,2015-16,Transmission lines maintenance,Transmission tower support structures,$0's,1.001427e+06,3.378777e+06,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,51
2,2015-16,Transmission lines maintenance,Conductors,$0's,2.358642e+05,1.872119e+06,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,52
3,2015-16,Transmission lines maintenance,Transmission cables,$0's,4.868219e+05,1.220075e+05,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,53
4,2015-16,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),$0's,2.166652e+06,4.253544e+06,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,54
5,2015-16,Substations equipment & property maintenance,Substation power transformers,$0's,9.761596e+05,2.288708e+06,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,55
6,2015-16,Substations equipment & property maintenance,Substation property,$0's,3.913647e+06,4.078866e+06,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,56
7,2015-16,SCADA & network control maintenance,SCADA & network control maintenance,$0's,1.760423e+06,2.700486e+05,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,57
8,2015-16,Protection systems maintenance,Protection systems maintenance,$0's,2.048702e+06,9.748460e+05,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,58
9,2015-16,Other maintenance activity,Row Maintenance,$0's,1.872730e+06,1.300828e+05,Copy of D16 147530(V3) ElectraNet 2015-16 - C...,2.8 Maintenance,59

{'descriptor_metrics': {'maintenance_activity': 'B10',
  'maintenance_asset_category': 'C10',
  'measure_asset_quantity': 'D10',
  'source_unit': 'E10',
  'asset_quantity_at_year_end': 'F10',
  'quantity_inspected_maintained': 'G10',
  'average_age_of_asset_group': 'H9',
  'inspection_cycle_years': 'I9',
  'maintenance_cycle_years': 'J9'},
 'cost_metrics': {'maintenance_activity': 'B48',
  'maintenance_asset_subcategory': 'C48',
  'routine_maintenance_expenditure': 'F48',
  'non_routine_maintenance_expenditure': 'G48',
  'source_currency_unit': 'F47'}}

[maintenance] Opening data\raw\Powerlink 2020-21 - Category Analysis - RIN Response - Consolidated - 20 October 2021 - PUBLIC(12941266.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=11, cost rows=11

,reporting_period,maintenance_activity,maintenance_asset_category,measure_asset_quantity,source_unit,asset_quantity_at_year_end,quantity_inspected_maintained,average_age_of_asset_group,inspection_cycle_years,maintenance_cycle_years,source_workbook,source_sheet,source_row
0,2020-21,Transmission lines maintenance,Transmission towers,Number of towers,0's,23550.00,23550.00,32.12,1.000,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,12
1,2020-21,Transmission lines maintenance,Transmission tower support structures,Number of towers,0's,23550.00,23550.00,32.12,1.000,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,13
2,2020-21,Transmission lines maintenance,Conductors,Route length,km,9629.00,9629.00,30.00,1.000,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,14
3,2020-21,Transmission lines maintenance,Transmission cables,Route length,km,20.24,20.24,23.07,1.000,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,15
4,2020-21,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),Number of switchbays,0's,1482.00,1482.00,18.09,0.500,6.0,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,16
5,2020-21,Substations equipment & property maintenance,Substation power transformers,Number of transformers,0's,201.00,201.00,20.18,0.500,6.0,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,17
6,2020-21,Substations equipment & property maintenance,Substation property,Number of substation properties maintained,0's,128.00,128.00,29.83,0.500,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,18
7,2020-21,SCADA & network control maintenance,SCADA & network control maintenance,Comms and SCADA equipment,NaN,6212.00,6212.00,11.48,1.000,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,19
8,2020-21,Protection systems maintenance,Protection systems maintenance,Protection relays,NaN,5030.00,5030.00,11.12,6.000,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,20
9,2020-21,Other maintenance activity,Tramsission tower support structures,Insulator Strings (000's),NaN,168.50,1457.00,17.76,5.782,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,21
10,2020-21,NaN,Corridor maintenance (Non vegetation),Length (Route km),km,9636.00,1363.00,32.12,1.000,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,22

,reporting_period,maintenance_activity,maintenance_asset_subcategory,source_currency_unit,routine_maintenance_expenditure,non_routine_maintenance_expenditure,source_workbook,source_sheet,source_row
0,2020-21,Transmission lines maintenance,Transmission towers,$0's,2840936.000,7.773311e+06,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,50
1,2020-21,Transmission lines maintenance,Transmission tower support structures,$0's,53017.600,2.895017e+07,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,51
2,2020-21,Transmission lines maintenance,Conductors,$0's,0.000,7.237803e+05,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,52
3,2020-21,Transmission lines maintenance,Transmission cables,$0's,220444.880,8.548250e+06,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,53
4,2020-21,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),$0's,4583217.588,1.474176e+07,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,54
5,2020-21,Substations equipment & property maintenance,Substation power transformers,$0's,1544174.417,3.412554e+06,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,55
6,2020-21,Substations equipment & property maintenance,Substation property,$0's,1485737.925,4.014438e+06,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,56
7,2020-21,SCADA & network control maintenance,SCADA & network control maintenance,$0's,1119461.830,5.362256e+06,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,57
8,2020-21,Protection systems maintenance,Protection systems maintenance,$0's,979355.020,2.260944e+06,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,58
9,2020-21,Other maintenance activity,Tramsission tower support structures,$0's,NaN,NaN,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,59
10,2020-21,NaN,Corridor maintenance (Non vegetation),$0's,5554.470,3.970319e+05,Powerlink 2020-21 - Category Analysis - RIN Re...,2.8 Maintenance,60

{'descriptor_metrics': {'maintenance_activity': 'B10',
  'maintenance_asset_category': 'C10',
  'measure_asset_quantity': 'D10',
  'source_unit': 'E10',
  'asset_quantity_at_year_end': 'F10',
  'quantity_inspected_maintained': 'G10',
  'average_age_of_asset_group': 'H9',
  'inspection_cycle_years': 'I9',
  'maintenance_cycle_years': 'J9'},
 'cost_metrics': {'maintenance_activity': 'B48',
  'maintenance_asset_subcategory': 'C48',
  'routine_maintenance_expenditure': 'F48',
  'non_routine_maintenance_expenditure': 'G48',
  'source_currency_unit': 'F47'}}

[maintenance] Opening data\raw\Transgrid 2022-23 - Category analysis - RIN response - Consolidated - 31 October 2023 - PUBLIC(15993699.2).xlsx
[maintenance] Detected stacked_revised; descriptor rows=11, cost rows=12

,reporting_period,maintenance_activity,maintenance_asset_category,measure_asset_quantity,source_unit,asset_quantity_at_year_end,quantity_inspected_maintained,average_age_of_asset_group,inspection_cycle_years,maintenance_cycle_years,source_workbook,source_sheet,source_row
0,2022-23,Transmission lines maintenance,Transmission towers,Number of towers,number,37308.000,9499.000,40.560000,5.450000,5.010000,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,13
1,2022-23,Transmission lines maintenance,Transmission tower support structures,Number of towers,number,NaN,NaN,NaN,NaN,NaN,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,14
2,2022-23,Transmission lines maintenance,Conductors,Route length,km,11233.240,3587.000,45.774370,3.390000,NaN,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,15
3,2022-23,Transmission lines maintenance,Transmission cables,Route length,km,90.785,90.785,18.184992,0.086849,1.814287,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,16
4,2022-23,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),Number of switchbays,number,2341.000,516.000,33.600000,0.500000,5.700000,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,17
5,2022-23,Substations equipment & property maintenance,Substation power transformers,Number of transformers,number,215.000,202.000,20.200000,0.500000,5.500000,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,18
6,2022-23,Substations equipment & property maintenance,Substation property,Number of substation properties maintained,number,96.000,96.000,38.900000,0.500000,0.300000,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,19
7,2022-23,SCADA & network control maintenance,SCADA & network control maintenance,Number,0's,1977.000,173.000,12.000000,NaN,NaN,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,20
8,2022-23,Protection systems maintenance,Protection systems maintenance,Number,0's,3240.000,1021.000,15.600000,NaN,6.400000,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,21
9,2022-23,Other maintenance activity,Metering,Number,0's,855.000,540.000,10.200000,2.500000,5.000000,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,22
10,2022-23,NaN,Communications,Number,0's,1787.000,981.000,9.600000,0.700000,3.000000,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,23

,reporting_period,maintenance_activity,maintenance_asset_subcategory,source_currency_unit,routine_maintenance_expenditure,non_routine_maintenance_expenditure,source_workbook,source_sheet,source_row
0,2022-23,Transmission lines maintenance,Transmission towers,$,5452948.0,8181433.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,51
1,2022-23,Transmission lines maintenance,Transmission tower support structures,$,NaN,NaN,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,52
2,2022-23,Transmission lines maintenance,Conductors,$,471823.0,603304.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,53
3,2022-23,Transmission lines maintenance,Transmission cables,$,734356.0,418379.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,54
4,2022-23,Substations equipment & property maintenance,Substation switchbays (incl. Reactive plant),$,1454533.0,2611448.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,55
5,2022-23,Substations equipment & property maintenance,Substation power transformers,$,1560406.0,1464114.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,56
6,2022-23,Substations equipment & property maintenance,Substation property,$,6165173.0,7152146.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,57
7,2022-23,SCADA & network control maintenance,SCADA & network control maintenance,$,32712.0,510468.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,58
8,2022-23,Protection systems maintenance,Protection systems maintenance,$,1150739.0,617753.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,59
9,2022-23,Other maintenance activity,Metering,$,499217.0,220259.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,60
10,2022-23,NaN,Communications,$,400286.0,1439324.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,61
11,2022-23,NaN,Bushfire Remediation,$,NaN,18157008.0,Transgrid 2022-23 - Category analysis - RIN re...,2.8 Maintenance,62

{'descriptor_metrics': {'maintenance_activity': 'B11',
  'maintenance_asset_category': 'C11',
  'measure_asset_quantity': 'D11',
  'source_unit': 'E11',
  'asset_quantity_at_year_end': 'F11',
  'quantity_inspected_maintained': 'G11',
  'average_age_of_asset_group': 'H10',
  'inspection_cycle_years': 'I10',
  'maintenance_cycle_years': 'J10'},
 'cost_metrics': {'maintenance_activity': 'B49',
  'maintenance_asset_subcategory': 'C49',
  'routine_maintenance_expenditure': 'F49',
  'non_routine_maintenance_expenditure': 'G49',
  'source_currency_unit': 'F48'}}

In [42]:
# try extracting Maintenance data across all RIN workbooks
results = {}
for file in excel_files:
    results[file] = extract_rin_maintenance(file)

[maintenance] Opening data\raw\AusNet (T) 2020-21 - Category Analysis - RIN Response - Consolidated - 29 July 2021 - PU(12595757.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Opening data\raw\AusNet (T) 2021-22 - Category Analysis - RIN Response - Consolidated - 28 July 2022 - PUBLIC(14205738.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Opening data\raw\Ausnet Services (ET) 2022-23 - Category Analysis - RIN Response - Consolidated - 28 July 2023 - PUBLIC(15600825.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Opening data\raw\Ausnet Services (ET) 2023-24 - Category Analysis - RIN Response - Consolidated - 26 July 2024 - PUBLIC(17069098.2).xlsx
[maintenance] Detected stacked_revised; descriptor rows=10, cost rows=10
[maintenance] Opening data\raw\Copy of D14-00150087(V02) - transgrid (t) 2013-14 - category analysis rin response - templates - consolidated - 31 october 2014 - public.xlsm
[maintenance] Detected legacy_side_by_side; descriptor rows=11, cost rows=12
[maintenance] Warning: descriptor_metrics: optional heading 'source_unit' was not found
[maintenance] Opening data\raw\Copy of D16 147530(V3)  ElectraNet 2015-16 - Category Analysis RIN Response - Public Version - 31 October 2016 - PUBLIC.xlsm
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Warning: descriptor_metrics: nonnumeric values in maintenance_cycle_years: row 12: 'Nil. Cond mon.&corr mtce'; row 13: 'Nil. Cond mon.&corr mtce'; row 14: 'Nil. Cond mon.&corr mtce'; row 15: 'Nil. Cond mon.&corr mtce'; row 19: 'Nil. Cond mon.&corr mtce'
[maintenance] Warning: descriptor_metrics: unrecognized source units in source_unit: ["000' KM"]
[maintenance] Opening data\raw\Copy of D17 153782  ElectraNet 2016-17 - Category Analysis RIN - Template - 31 October 2017 - PUBLIC.xlsm
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Warning: descriptor_metrics: nonnumeric values in maintenance_cycle_years: row 12: 'Nil. Cond mon.&corr mtce'; row 13: 'Nil. Cond mon.&corr mtce'; row 14: 'Nil. Cond mon.&corr mtce'; row 15: 'Nil. Cond mon.&corr mtce'; row 19: 'Nil. Cond mon.&corr mtce'
[maintenance] Opening data\raw\DORIS - D18-158142 Transgrid 2017-18 - Category Analysis RIN - Templates - Public.XLSM
[maintenance] Detected stacked_baseline; descriptor rows=11, cost rows=11
[maintenance] Opening data\raw\DORIS - D18-158267 ElectraNet 2017-18 - Category Analysis RIN - Template - Public.XLSM
[maintenance] Detected stacked_baseline; descriptor rows=11, cost rows=11
[maintenance] Warning: descriptor_metrics: nonnumeric values in maintenance_cycle_years: row 12: 'Nil. Cond mon.&corr mtce'; row 13: 'Nil. Cond mon.&corr mtce'; row 14: 'Nil. Cond mon.&corr mtce'; row 15: 'Nil. Cond mon.&corr mtce'; row 19: 'Nil. Cond mon.&corr mtce'
[maintenance] Opening data\raw\ElectraNet 2018-19 - Category Analysis - RIN Response - Consolidated - 31 October 2019 - PUBLIC D19-175655.xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Warning: descriptor_metrics: nonnumeric values in maintenance_cycle_years: row 12: 'Nil. Cond mon.&corr mtce'; row 13: 'Nil. Cond mon.&corr mtce'; row 14: 'Nil. Cond mon.&corr mtce'; row 15: 'Nil. Cond mon.&corr mtce'; row 19: 'Nil. Cond mon.&corr mtce'
[maintenance] Opening data\raw\ElectraNet 2019-20 - Category Analysis - RIN Response - Consolidated - 30 October 2020 - PUBLIC (#11672792).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Warning: descriptor_metrics: nonnumeric values in maintenance_cycle_years: row 12: 'Nil. Cond mon.&corr mtce'; row 13: 'Nil. Cond mon.&corr mtce'; row 14: 'Nil. Cond mon.&corr mtce'; row 15: 'Nil. Cond mon.&corr mtce'; row 19: 'Nil. Cond mon.&corr mtce'
[maintenance] Opening data\raw\ElectraNet 2020-21 - Category Analysis - RIN Response - Consolidated - 29 October 2021 - PUBLIC(13029806.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Warning: descriptor_metrics: nonnumeric values in maintenance_cycle_years: row 12: 'Nil. Cond mon.&corr mtce'; row 13: 'Nil. Cond mon.&corr mtce'; row 14: 'Nil. Cond mon.&corr mtce'; row 15: 'Nil. Cond mon.&corr mtce'; row 19: 'Nil. Cond mon.&corr mtce'
[maintenance] Opening data\raw\ElectraNet 2021-22 - Category Analysis - RIN response - 28 October 2022 - PUBLIC(14582813.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Warning: descriptor_metrics: nonnumeric values in maintenance_cycle_years: row 12: 'Nil. Cond mon.&corr mtce'; row 13: 'Nil. Cond mon.&corr mtce'; row 14: 'Nil. Cond mon.&corr mtce'; row 15: 'Nil. Cond mon.&corr mtce'; row 19: 'Nil. Cond mon.&corr mtce'
[maintenance] Opening data\raw\ElectraNet 2022-23 - Category analysis - RIN responses - Consolidated - 27 October 2023 - PUBLIC(15999621.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=10, cost rows=10
[maintenance] Warning: descriptor_metrics: nonnumeric values in maintenance_cycle_years: row 12: 'Nil. Cond mon.&corr mtce'; row 13: 'Nil. Cond mon.&corr mtce'; row 14: 'Nil. Cond mon.&corr mtce'; row 15: 'Nil. Cond mon.&corr mtce'; row 19: 'Nil. Cond mon.&corr mtce'
[maintenance] Opening data\raw\ElectraNet 2023-24 - Category Analysis - RIN response - Consolidated - 31 October 2024 - PUBLIC(17494700.2).xlsx
[maintenance] Detected stacked_revised; descriptor rows=10, cost rows=10
[maintenance] Opening data\raw\Powerlink 2020-21 - Category Analysis - RIN Response - Consolidated - 20 October 2021 - PUBLIC(12941266.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=11, cost rows=11
[maintenance] Opening data\raw\Powerlink 2021-22 - Category analysis - Consolidated - 26 October 2022 - PUBLIC(14556313.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=11, cost rows=11
[maintenance] Opening data\raw\Powerlink 2022-23 - Category Analysis - RIN Response - Consolidated - 27 October 2023 - PUBLIC(15996094.1).xlsx
[maintenance] Detected stacked_revised; descriptor rows=11, cost rows=11
[maintenance] Opening data\raw\Powerlink 2023-24 - Category Analysis - RIN Response - Consolidated - 28 October 2024 - PUBLIC(17452408.1).xlsx
[maintenance] Detected stacked_revised; descriptor rows=11, cost rows=11
[maintenance] Opening data\raw\Transgrid 2018-19 - Category Analysis - RIN Response - Consolidated - 31 October 2019 - PUBLIC D19-175594.XLSM.xlsx
[maintenance] Detected stacked_baseline; descriptor rows=11, cost rows=11
[maintenance] Opening data\raw\TransGrid 2019-20 - Category Analysis - RIN Response - Consolidated - 30 October 2020 - PUBLIC (#11,665,158).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=11, cost rows=12
[maintenance] Opening data\raw\TransGrid 2020-21 - Category Analysis - RIN Response - Consolidated - 29 October 2021 - PUBLIC(13029988.1).xlsx
[maintenance] Detected stacked_baseline; descriptor rows=11, cost rows=12
[maintenance] Opening data\raw\Transgrid 2022-23 - Category analysis - RIN response - Consolidated - 31 October 2023 - PUBLIC(15993699.2).xlsx
[maintenance] Detected stacked_revised; descriptor rows=11, cost rows=12
[maintenance] Opening data\raw\Transgrid 2023-24 - Category Analysis - RIN Response - Consolidated - 31 October 2024 - PUBLIC(17496053.2).xlsx
[maintenance] Detected stacked_revised; descriptor rows=11, cost rows=11

In [ ]:
{k:v for k,v in results.items() if v.warnings}

AttributeError: 'WindowsPath' object has no attribute 'warnings'